### ISSUE TITLE
Increasing Title Tag for SEO

### ISSUE THREAD

**Issue by dchen97** [oppia/foundation-website#108]
Tag title Oppia Foundation is not optimized. Title should be between 55 to 66 characters. Missing `<h1>` tag within the page.

**Comment by hoangviet1993** [comment]
So here is our title tag on index.html:
```Javascript
<title ng-bind="$root.title">Oppia Foundation</title>
```
What should the title be to reach the 55 characters length?

> 

> Missing `<h1>` tag within the page.

What do you mean by this? Which page? The home page currently has a h1 tag.

**Comment by ashiscs** [comment]
Hi, is this issue still open?
I would like to contribute.

**Comment by itsameaditya** [comment]
Hey I could contribute regarding this SEO issue.
Admin, please assign this issue to me

**Comment by Swastik-123** [comment]
Can anyone help me a bit to understand this problem

**Comment by Swastik-123** [comment]
and also which page i need to put `<h1>`

**Comment by seanlip** [comment]
We are no longer working on this -- closing this issue.

**Comment by Swastik-123** [comment]
Ok
