### ISSUE TITLE
Custom 404 Error Page

### ISSUE THREAD

**Issue by dchen97** [oppia/foundation-website#109]
The website does not have a 404 Error Page. This damages the site's usability. A custom 404 page can help reduce end user frustration and link to other pages on site.

**Comment by hoangviet1993** [comment]
Thanks @dchen97!

Sean and I talked about 404 Error page on #30. What do you think?

**Comment by sun-fox** [comment]
I am new to oppia, If this is the issue still open I would like to work on this.

**Comment by apsychogirl** [comment]
Hi, is this still available to work upon? If yes, I would like to work upon it.

**Comment by seanlip** [comment]
Sorry, no it's not. We are planning to move these pages into the main Oppia website so designing a custom 404 page for this site is probably not needed. Thanks for checking!
