### ISSUE TITLE
CSS File Minification for SEO

### ISSUE THREAD

**Issue by dchen97** [oppia/foundation-website#110]
Need to minify CSS files to improve SEO performance.

**Comment by hoangviet1993** [comment]
I think we can try to minify all of the Foundation site's files,  similar to that of Oppia. @seanlip, What do you think?

**Comment by seanlip** [comment]
I have no objection to adding a build script, yeah.

**Comment by The-Fuse** [comment]
I would like to work on this issue.

**Comment by seanlip** [comment]
Closing this since we don't plan to work on it.
