### ISSUE TITLE
Optimize and Compress Images

### ISSUE THREAD

**Issue by dchen97** [oppia/foundation-website#111]
Compressing and resizing https://oppiafoundation.org/assets/images/home/home_impact.jpg could save 60.9KiB (73% reduction).

Compressing https://oppiafoundation.org/assets/images/navbar/oppia_foundation_logo.png could save 1.2KiB (30% reduction).

**Comment by hoangviet1993** [comment]
Hi @dchen97 what are you using to compress the images to get the result you mention?

**Comment by iharshit009** [comment]
I have a suggestion...
can we use webp format to compress the size of images??
@dchen97

**Comment by hoangviet1993** [comment]
Thanks @iharshit009  for the suggestion!

I individually compressed all images before putting them in the repo. I could use a different tool to further compress them.

@iharshit009 How do you think Webp will help with compression? Have you had experience converting jpeg to webp? I can get you the original uncompressed version if you want to give it a try!

**Comment by iharshit009** [comment]
Yes I have worked on a project where I converted jpeg to webp format so as
to optimise the webpage...

I would feel honoured if I could get a chance to look at the issue and work
for optimisation...
Please share the original uncompressed version. I will look into and revert
you soon

**Comment by hoangviet1993** [comment]
So I did some digging and managed to find the original source of the photo.
@iharshit009 Would you mind going to my provided link, click "Free Download" and then select "Original"? A year ago, I was emailed the photo by the designer at the time and it was around 5MB.
https://www.maxpixel.net/Different-Happy-Faces-Children-Rural-Drawings-1853193

**Comment by iharshit009** [comment]
Thanks for your email, I would look into it soon.

**Comment by nlok5923** [comment]
i would like to work on this issue if nobody is working

**Comment by gurramkarthiknetha** [comment]
I want to take this up this issue if you are not solving...

**Comment by seanlip** [comment]
Closing since we are no longer maintaining this project.
