### ISSUE TITLE
Page should redirect for URLs ending with a trailing slash.

### ISSUE THREAD

**Issue by seanlip** [oppia/foundation-website#124]
To reproduce:

1. Go to https://www.oppiafoundation.org/blah/

Expected behaviour: There is a redirect to the home page.

Observed behaviour: A blank page with some odd artifacts shows up. No redirect happens.

**Comment by seanlip** [comment]
/cc @hoangviet1993 -- would you be able to look into this, please? It looks quite odd.

Thanks!

**Comment by hoangviet1993** [comment]
I think this is a trailing slash issue? If you take a valid url like [oppiafoundation.org/about](https://oppiafoundation.org/about) and append a trailing slash to it, you would reproduce the bug. One interesting note is that you have to append the slash directly yourself, linking the page would not replicate the bug.

Try clicking it here: [https://oppiafoundation.org/about/](https://oppiafoundation.org/about/)

I have been looking up potential solutions and so far, no quick hacks unfortunately.

I have seen a few SO popping up about ui-router's [strictMode](https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-make-a-trailing-slash-optional-for-all-routes) would get rid of trailing slashes in URL. However, that means I would have to bring in ui-router in place of the AngularJS's routeProvider that we are currently using.

How should we handle this bug? More investigation?

**Comment by seanlip** [comment]
Yes, I think it is a trailing slash issue, and that it needs more investigation. Some thoughts:

- Perhaps the regexes in app.yaml can be modified to allow for a trailing slash.
- For the URL routing in main.py there should perhaps be a "catch-all" handler that either goes to a 404 page, or redirects to the main page? We should probably also ensure that each URL pattern allows for a trailing slash, too.

What do you think?

**Comment by rajk1121** [comment]
I am having this error.Please help
![os](https://user-images.githubusercontent.com/34133408/64850161-7e77cc80-d632-11e9-90c7-4b693c0a4d80.PNG)

**Comment by rajk1121** [comment]
Any help will be appreciated sir.

**Comment by seanlip** [comment]
I have never seen this error before, sorry. But one thought might be that google_appengine didn't download properly. Do you have a wrapper_util.py in the top level of the google_appengine/ folder (alongside dev_appserver.py and run_tests.py)? If not, then that might signal an incomplete download. If so, I'm not sure what's going on -- you might need to look at how Python handles imports in general, maybe something else on your sys.path is interfering with trying to figure out where to import the library from.

**Comment by SaravgiYash** [comment]
Hi, @seanlip I would like to work on this issue. Can you please guide me on what all changes do I need to make?
After some surfing, I found that we need to write a rule in htaccess code to redirect them.

**Comment by seanlip** [comment]
Sorry, I don't know what changes need to be made here -- that's part of what whoever takes up the issue would need to figure out. It requires some investigation. I don't think it is related to htaccess, though, because this site does not run on an Apache Web Server.

**Comment by Ayushsunny** [comment]
I wanna work on this issue

**Comment by seanlip** [comment]
Thanks for your interest, @Ayushsunny. We are planning to combine the pages here with that of the main site, so it is probably not worthwhile to work on this issue. I'm going to close it.
