### ISSUE TITLE
Volunteer name is accepted even if it is just numbers.

### ISSUE THREAD

**Issue by ahv15** [oppia/foundation-website#126]
**Problem:**

While filling in the name in the volunteer form (at this page https://www.oppiafoundation.org/volunteer ) even if the entire name is just numbers it is accepted.

**Current Behaviour:**

![output (1)](https://user-images.githubusercontent.com/52852877/71572224-188d5300-2b04-11ea-9104-a72c5f714d74.png)

**Expected Behaviour:**
Allow only names containing upper or lower case alphabets.
![output (2)](https://user-images.githubusercontent.com/52852877/71572276-42df1080-2b04-11ea-8141-f09a5412c290.png)
**Would you like to work on the issue?**
Yes

**Comment by seanlip** [comment]
Hi @ahv15, thanks for filing this. We don't intend to fix it, though -- if we get responses like this (that are  non-understandable), we probably just won't follow up.

**Comment by ahv15** [comment]
Sorry for the problem in stating the issue, 
 which occurs while trying to volunteer in the volunteer page .(https://www.oppiafoundation.org/volunteer)
While submitting the name in the volunteer form even if the name is a number(eg-163639) it is accepted but as the volunteers name can't be a number it should not be accepted.

**Comment by seanlip** [comment]
Yes, I understand the issue. Thank you for filing it. We may still decide not to follow up with applications which we cannot understand.

**Comment by ahv15** [comment]
Ok
