### ISSUE TITLE
Video does not load in home page.

### ISSUE THREAD

**Issue by ahv15** [oppia/foundation-website#127]
**Problem:**
The video in the home page does not load when used in firefox, OS-Ubuntu 18.04.
**Current Behaviour:**
As firefox in Ubuntu does does not support mp4 the video in homepage does not load.
![Screenshot from 2020-01-03 14-32-04](https://user-images.githubusercontent.com/52852877/71715532-b00de100-2e37-11ea-8ffe-68066e165db2.png)
**Expected Behaviour**
As firefox in Ubuntu supports Ogg, the video loads if Interactions_video.ogg is present as an additional file.
![Screenshot from 2020-01-03 14-32-08](https://user-images.githubusercontent.com/52852877/71715698-52c65f80-2e38-11ea-84e0-35331a23aa0b.png)
**Would you like to work on the issue?**
Yes

**Comment by seanlip** [comment]
I'm a bit confused. I just visited the page with Firefox on Ubuntu and the video works fine.

See the later part of [this answer](https://stackoverflow.com/a/14536659) -- do you have an older version of Firefox? The one I'm using at the moment is 71.0.

**Comment by ahv15** [comment]
I just verified it and I am also using 71.0
![Screenshot from 2020-01-04 09-24-57](https://user-images.githubusercontent.com/52852877/71759534-57d8ec80-2ed4-11ea-9654-59a8fc98d125.png)

**Comment by ahv15** [comment]
Looks like additional files have to be installed before mp4 loads in firefox and those files around 170 MB should be downloaded separately as it is not always included.
[https://askubuntu.com/questions/879672/video-js-wont-playback-in-firefox-video-mp4-is-not-supported-warning?rq=1](url)

**Comment by ahv15** [comment]
But still adding the Ogg file could save people some time and effort.

**Comment by seanlip** [comment]
Thanks for the investigation! I think, on balance, let's leave it as-is. (People would need to update their browser in any case, since otherwise they are going to have trouble viewing videos in other sites anyway.)
