### ISSUE TITLE
Adjust Partnerships Page to give more background on Advocacy Program

### ISSUE THREAD

**Issue by dchen97** [oppia/foundation-website#134]
Edit content of Partnerships page so that it is in line with [this PRD](https://docs.google.com/document/d/1kPaEdKOXqCfs3I6qi8wCD82gwuPDLMxfKJBjku5sYzQ/edit#): https://docs.google.com/document/d/1kPaEdKOXqCfs3I6qi8wCD82gwuPDLMxfKJBjku5sYzQ/edit#

**Comment by Ayushsunny** [comment]
I wanna work on this issue

**Comment by abhijain2003** [comment]
can you give brief explaination of issue

**Comment by seanlip** [comment]
Closing this issue since the partnership page is moving to the main oppia site.

@dchen97 not sure if we need to open a replacement issue on oppia/oppia?
