### ISSUE TITLE
Error 404 while opening the 'Get Started' page

### ISSUE THREAD

**Issue by LalitChauhan56** [oppia/foundation-website#157]
The website throws an 404 error when the 'Get Started' link is opened on the footer of the page.

![Screenshot 2023-11-22 150902](https://github.com/oppia/foundation-website/assets/73524110/04068482-510c-4ab4-aeb6-730d5ece43a2)

![image](https://github.com/oppia/foundation-website/assets/73524110/6e6b7aaa-f9a6-46ca-b82f-e841d00466ee)

**Comment by LalitChauhan56** [comment]
Is there any pre-existing page which should be displayed here or do we have to make a new one? I would be happy to help.

**Comment by PrnvCodr** [comment]
i can help ya with this :)

**Comment by seanlip** [comment]
Thanks for filing this. We are actually deprecating the foundation website and planning to redirect everything to the main oppia website, so I suggest not working on this for now. If you'd like to help please look at the list of issues for the main Oppia website which you can find here: https://github.com/oppia/oppia/issues . Thanks!

**Comment by LalitChauhan56** [comment]
Sounds great. I will look into the issues in the main oppia website.
