### ISSUE TITLE
Volunteer page content should be deduplicated

### ISSUE THREAD

**Issue by seanlip** [oppia/foundation-website#77]
While working on #76, I found that the content for the volunteer tabs was duplicated in multiple places and that the bullet points describing what each team does were out of sync in both. I fixed this, but clearly missed that there were two occurrences in an earlier PR. That said, there really shouldn't be two occurrences in the first place.

So, the aim of this issue is to find a way to consolidate the data on each card so that there is a single source of truth for that data and it is automatically used in both places. (Note that it's better to use templates for this, rather than JavaScript strings containing HTML.)

/cc @hoangviet1993

**Comment by hoangviet1993** [comment]
From my perspective, the common structure that can be templated is the bullet points.
```HTML
<ul>
  <li>...</li>
 <li>...</li>
 <li>...</li>
</ul>
```
I can try to imitate how the current tab system works:

1. Turn these bullet points into individual HTML templates named something like `design_description.html`,`development_description.html`, etc., ...
2. I would then have a scope variable mapping an array index to each template Url:
```javascript
$scope.volunteerWorkDescription['design'] = {
  templateUrl: '/pages/volunteer/description_templates/design_description.html'
};
```
3. Subsequently, in `volunteeer.html` or elsewhere, I would be using ng-include like:
`<ng-include src="volunteerWorkDescription['design'].templateUrl"><ng-include>`
@seanlip sound good to you?

**Comment by seanlip** [comment]
Yes, that sounds like a reasonable approach. Thanks!
