### ISSUE TITLE
No links in follow us option

### ISSUE THREAD

**Issue by HarshCic** [oppia/foundation-website#99]
**I'm submitting a ...**
   Feature request
**Current behavior:**
   The follow us option doesn't have any any links.
![Screenshot from 2019-04-05 19-43-02](https://user-images.githubusercontent.com/37294414/55634740-b275d880-57dc-11e9-94ca-e8723d0b1014.png)

**Expected behavior:**
   There should be Icons with links to the pages of Oppia Foundation.
**Would you like to work on the issue?**
   Yes

**Comment by seanlip** [comment]
That's odd. I believe there are links -- see image below.

![Screenshot from 2019-04-05 12-09-37](https://user-images.githubusercontent.com/10575562/55650903-d95fea80-579b-11e9-93cc-2583c4b4127f.png)


Do they appear when you check the page source?

**Comment by HarshCic** [comment]
I'm using Google Chrome.. and I can clearly see that these icons are throwing errors while loading as they are not loading in web page during Inspect element also and i can see those errors on the console of chrome debugger.

**Comment by seanlip** [comment]
Ah, ok, thanks. Could you paste a screenshot of the errors? If there are
any "collapsibles" in the console, please expand them.

Also, what OS and version of Chrome are you using?

**Comment by HarshCic** [comment]
Google Chrome -Version 70.0.3538.67 (Official Build) (64-bit)
OS- Ubuntu 16.04
I will post the screenshots in a  bit.

**Comment by anandwana001** [comment]
Seems like this issue is resolved. @HarshCic
